# Generated by Django 4.0.10 on 2023-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedId', models.IntegerField(null=True)),
                ('linkPrecedence', models.CharField(choices=[('p', 'primary'), ('s', 'secondary')], default='p', max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
