# Generated by Django 4.0.10 on 2023-07-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_email_alter_contact_linkprecedence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
