# Generated by Django 4.0.10 on 2023-07-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='deletedAt',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkPrecedence',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', editable=False, max_length=15),
        ),
    ]
