# Generated by Django 4.0.10 on 2023-07-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_deletedat_alter_contact_linkprecedence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='linkedId',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
